version: '3'
services:
  client:
    image: "siving/multi-client"
    mem_limit: 128m
    hostname: client # Hostname that can be accessed by other containers
  server:
    image: "siving/multi-server"
    mem_limit: 128m
    hostname: api # Hostname used by other containers
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGDATABASE
      - PGPORT=$PGPORT
  worker:
    image: "siving/multi-worker"
    mem_limit: 128m
    hostname: worker # Hostname not required here, but nice to have defined
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "siving/multi-nginx"
    mem_limit: 128m
    hostname: nginx # Hostname not required here, but nice to have defined
    ports:
      - "80:80"
